# Configuration for the Knowledge Base Preparation Script

# --- Directory Settings ---
# Paths for input, output, and the final report.
source_directory: "source_pdfs/scanned_files" # You can put any supported file type here
output_directory: "outputs/knowledge_base"
report_path: "outputs/report.json"

# --- File Types to Process ---
# Add the extensions of the file types you want to include.
file_types:
  - ".pdf"
  - ".epub"
  - ".docx"
  - ".txt"

# --- Processing Limits ---
# Set the maximum number of tokens and file size (in MB) for each merged file.
# Note: Size limit is checked for source files, but the final text output size will vary.
max_tokens_per_file: 2000000
max_file_size_mb: 512

# --- Model and Feature Toggles ---
# Specify the model for tokenization and enable/disable OCR processing for PDFs.
tiktoken_model: "gpt-4o"
use_ocr: false


# --- Optional External Tool Paths ---
# Provide the absolute path to your Poppler 'bin' directory if it's not in your system's PATH.
# Set to null or remove the line if Poppler is in your PATH.
# Example for macOS Homebrew: "/opt/homebrew/bin"
# Example for Windows: "C:/path/to/poppler-22.04.0/Library/bin"
poppler_path: "/opt/homebrew/opt/poppler/bin"
tesseract_cmd: "/opt/homebrew/bin/tesseract"